services:

  booking_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: denevy
      POSTGRES_PASSWORD: denevy
      POSTGRES_DB: bookingdb
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
